services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: devsecops-app
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: devsecops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: devsecops-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
