{
 "title": "DevSecOps Application Monitoring",
 "tags": [
  "devsecops",
  "flask",
  "prometheus",
  "mysql"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Uptime Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"devsecops-app\"}",
     "legendFormat": "App Target"
    }
   ]
  },
  {
   "title": "MySQL Database Connectivity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "devsecops_database_up or vector(0)",
     "legendFormat": "MySQL Status"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total) or vector(0)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Current Request Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m])) or vector(0)",
     "legendFormat": "Req / sec"
    }
   ]
  },
  {
   "title": "HTTP Request Count (Cumulative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flask_http_request_total or vector(0)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m]) or vector(0)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Average HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(flask_http_request_duration_seconds_sum[1m]) / rate(flask_http_request_duration_seconds_count[1m])) or vector(0)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[1m])) or vector(0)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  }
 ]
}