name: Test SSM
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-south-1
jobs:
  test-ssm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Test Command
        run: |
          set +e
          TS=$(date +%s)
          mkdir -p iam_output
          aws ssm describe-instance-information \
            --filters "Key=InstanceIds,Values=i-0fb9dcbeb35b4fdbe" \
            --region ap-south-1 \
            > iam_output/instance-info-$TS.json 2>&1
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add iam_output/
          git commit -m "Get instance info $TS" || true
          sleep 10
          git pull --rebase origin main
          git push origin main
