name: Test SSM Simple
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-south-1
jobs:
  test-ssm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Run SSM
        run: |
          set +e
          mkdir -p iam_output
          TS=$(date +%s)
          
          CMD_ID=$(aws ssm send-command \
            --instance-ids i-0fb9dcbeb35b4fdbe \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["echo Hello SSM", "pwd"]}' \
            --region ap-south-1 \
            --query "Command.CommandId" \
            --output text 2>&1)
            
          sleep 15
          
          aws ssm get-command-invocation \
            --command-id $CMD_ID \
            --instance-id i-0fb9dcbeb35b4fdbe \
            --region ap-south-1 > iam_output/simple-$TS.json 2>&1
            
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add iam_output/
          git commit -m "Test Simple $TS" || true
          git pull --rebase origin main
          git push origin main
